spring:
  application:
    name: coffee

  datasource:
    url: jdbc:mysql://localhost:3306/coffee?createDatabaseIfNotExist=true
    username: root
    password: 1038

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
